<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle('Issues') ?> 
        <?= $this->headLink()
                 ->appendStylesheet('/css/rebase-min.css')
                 ->appendStylesheet('/css/style.css') ?>
        <?= $this->headScript()
                 ->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js')
                 ->appendFile('/js/issues-global.js') ?>
        <link rel="shortcut icon" href="/images/icons/application_view_list.png" />
        <script type="text/javascript">
            $(document).ready(function() {
                autoPopulate('#siteSearchInput', '<?=$this->translate('search_box_label');?>');
                autoPopulate('#newLabelInput', '<?=$this->translate('new_label_name');?>');
            });
        </script>
    </head>
    <body>
        
        <div id="pageWrap">

            <div id="siteHeader" class="clearfix">
                <div id="siteTitle" class="floatLeft">
                    <?=$this->translate('issues');?>
                </div>
                <div id="accountInfo" class="floatRight">
                    <? if(Zend_Auth::getInstance()->getIdentity()->getRole()->getName() != 'guest'): ?>
                    Signed in as <?= Zend_Auth::getInstance()->getIdentity()->getUsername(); ?> | <a href="<?=$this->url(array('controller'=>'auth','action'=>'logout'), null, true);?>"><?= $this->translate('sign_out'); ?></a>
                    <? else: ?>
                    <a href="<?=$this->url(array('controller'=>'auth','action'=>'login'), null, true);?>"><?= $this->translate('sign_in'); ?></a> |
                    <a href="<?=$this->url(array('controller'=>'register','action'=>'index'), null, true);?>"><?=$this->translate('register');?></a>
                    <? endif; ?>
                </div>
            </div>
            
            <div class="clearfix">
                <ul id="primaryNavigation" class="tabList floatLeft">
                    <li class="active">
                        <a href="<?=$this->url(array('controller'=>'index','action'=>'index'), null, true);?>"><?=$this->translate('issues');?></a>
                    </li>
                    <li>
                        <a href="#">Projects</a>
                    </li>
                    <li>
                        <a href="#"><?=$this->translate('milestones');?></a>
                    </li>
                    <li>
                        <a href="#"><?=$this->translate('members');?></a>
                    </li>
                </ul>
                
                <form method="post" action="#" id="siteSearchForm" class="floatRight">
                    <label id="siteSearch" for="siteSearchInput">
                        <input type="text" name="siteSearchInput" tabIndex="1" id="siteSearchInput" />
                    </label>
                    <button type="submit" id="siteSearchButton"><?=$this->translate('go');?></button>
                </form>
            </div>
            
            <div class="tabListBottom">
                <ul class="tabListSubNav clearfix">
                    <li class="active">
                        <a href="#"><?=$this->translate('all_issues');?> (17)</a>
                    </li>
                    <li>
                        <a href="#"><?=$this->translate('my_issues');?> (3)</a>
                    </li>
                    <li>
                        <a href="#"><?=$this->translate('mentioning_you');?> (0)</a>
                    </li>
                    <li>
                        <a href="#"><?=$this->translate('unassigned_issues');?> (3)</a>
                    </li>
                </ul>
            </div>
            
            <div id="pageContent" class="clearfix">
                
                <?= $this->layout()->content; ?>
            
            </div>
            
        </div>
        
    </body>
    <!-- Page template by, Chris Kankiewicz <http://www.chriskankiewicz.com> -->
</html>
